image: ruby:2.3.3

services:
  - mysql:5.5
variables:
  MYSQL_ALLOW_EMPTY_PASSWORD: "Yes"
  DATABASE_URL: "mysql2://root@mysql:3306/tc_test"

test:
  script:
    - apt-get update -qq && apt-get install -y build-essential nodejs
    - bundle install --deployment --without production --quiet --path /cache
    - bundle exec rake db:create spec SPEC_OPTS="--format progress" SIMPLECOV=1
  tags:
    - ruby

rubocop:
  only:
    - master
  allow_failure: true
  script:
    - apt-get update -qq && apt-get install -y build-essential nodejs
    - bundle install --deployment --without production --quiet --path /cache
    - bundle exec rubocop --format simple
  tags:
    - ruby
