language: ruby
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE teamcontrol_test;'
  - cp config/database.yml.example config/database.yml
env:
  global:
    - SIMPLECOV=1
rvm:
  - "2.3.3"
