version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'teamcontrol_prod'
      MYSQL_USER: 'tc-root'
      MYSQL_PASSWORD: 'teamcontrol1337'
      MYSQL_ROOT_PASSWORD: 'teamcontrol1337'
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
  letsencrypt:
    image: certbot/certbot
    command: certonly --standalone --email [your-email-address] --agree-tos --no-eff-email -d [your-domain]
    volumes:
      - ./cert:/etc/letsencrypt
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert:/etc/letsencrypt
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    restart: always
    volumes:
      - .:/teamcontrol
    ports:
      - "3000:3000"
    environment:
      SECRET_KEY_BASE: 'f5f3d79142dd36b4e85a195834c31a036b3f4a64fecb5765c3a271a196e86c53608039abdd846e0ed14a2d5fb2f297f79fdc7a8d039c3daa89dfb1db2f2fef20'
      DB_USERNAME: 'tc-root'
      DB_PASSWORD: 'teamcontrol1337'
      DB_HOST: 'db'
    depends_on:
      - db
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"