version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: 'teamcontrol_prod'
      MYSQL_USER: 'tc-root'
      MYSQL_PASSWORD: 'teamcontrol1337'
      MYSQL_ROOT_PASSWORD: 'teamcontrol1337'
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql

  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 443:443
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./cert:/etc/nginx/cert
      - ./logs/nginx:/var/log/nginx/
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    restart: always
    volumes:
      - .:/teamcontrol
      - ./logs/rails:/app/log/
    ports:
      - "3000:3000"
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DB_USERNAME: 'tc-root'
      DB_PASSWORD: 'teamcontrol1337'
      DB_HOST: 'db:3306'
    depends_on:
      - db