version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'teamcontrol_prod'
      MYSQL_USER: 'tc-root'
      MYSQL_PASSWORD: 'teamcontrol1337'
      MYSQL_ROOT_PASSWORD: 'teamcontrol1337'
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
  letsencrypt:
    image: certbot/certbot
    command: certonly --standalone --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN}
    volumes:
      - ./cert/conf:/etc/letsencrypt
      - ./cert/www:/var/www/certbot
    depends_on:
      - reverse

  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert/conf:/etc/letsencrypt
      - ./cert/www:/var/www/certbot
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    restart: always
    volumes:
      - .:/teamcontrol
    ports:
      - "3000:3000"
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DB_USERNAME: 'tc-root'
      DB_PASSWORD: 'teamcontrol1337'
      DB_HOST: 'db'
    depends_on:
      - db