version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'teamcontrol_prod'
      MYSQL_USER: 'tc-root'
      MYSQL_PASSWORD: 'teamcontrol1337'
      MYSQL_ROOT_PASSWORD: 'teamcontrol1337'
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
  reverse:
    build:
      context: .
      dockerfile: reverseProxy.Dockerfile
      args:
        domain: yourdomain.com
        email: email@email.com
    hostname: reverse
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    restart: always
    volumes:
      - .:/teamcontrol
    ports:
      - "3000:3000"
    environment:
      SECRET_KEY_BASE: 'f5f3d79142dd36b4e85a195834c31a036b3f4a64fecb5765c3a271a196e86c53608039abdd846e0ed14a2d5fb2f297f79fdc7a8d039c3daa89dfb1db2f2fef20'
      DB_USERNAME: 'tc-root'
      DB_PASSWORD: 'teamcontrol1337'
      DB_HOST: 'db'
    depends_on:
      - db
